### ISSUE TITLE
[GRU4Rec] GRU4Rec doesn't use GPU 

### ISSUE THREAD

**Issue by mathslove** [asash/bert4rec_repro#3]
I tried to experiment with different models and encountered the problem that GRU4Rec takes much longer to train than other NNs. So I checked the logs and saw warnings saying that GRU layers are not using GPU optimization.
`WARNING:tensorflow:Layer gru will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU`

**Comment by asash** [comment]
Hi, I merged your fix.
